name: CI Ansible

on:
  push:
    branches:
      - main
      - cadastro_POST
    paths:
      - 'configura-node.yaml'
      - '.github/workflows/pull-request-workflow.yml'
  pull_request:
    branches:
      - main
      - cadastro_POST

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Verificar sintaxe do playbook
        run: ansible-playbook --syntax-check configura-node.yaml
